name: masterthesis
channels:
  - defaults
dependencies:
#  - appnope=0.1.2
  - backcall=0.2.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - decorator=4.4.2
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
#  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libsodium=1.0.18
  - ncurses=6.2
  - openssl=1.1.1j
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prompt-toolkit=3.0.8
  - ptyprocess=0.7.0
  - pygments=2.8.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - pyzmq=20.0.0
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - adal==1.2.6
    - alembic==1.4.1
    - applicationinsights==0.11.9
    - argon2-cffi==20.1.0
    - argparse==1.4.0
    - asttokens==2.0.4
    - async-generator==1.10
    - attrs==20.3.0
    - autopep8==1.5.6
    - azure-common==1.1.27
    - azure-core==1.12.0
    - azure-graphrbac==0.61.1
    - azure-identity==1.4.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-keyvault==2.2.0
    - azure-mgmt-resource==12.1.0
    - azure-mgmt-storage==11.2.0
    - azure-storage-blob==12.8.0
    - azureml==0.2.7
    - azureml-core==1.25.0
    - azureml-dataprep==2.11.2
    - azureml-dataprep-native==30.0.0
    - azureml-dataprep-rslex==1.9.1
    - azureml-dataset-runtime==1.25.0
    - azureml-telemetry==1.25.0
    - azureml-train==1.25.0
    - azureml-train-core==1.25.0
    - azureml-train-restclients-hyperdrive==1.25.0
    - azureml-widgets==1.25.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - banal==1.0.6
    - bleach==3.3.0
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - contextlib2==0.6.0.post1
    - cryptography==3.4.7
    - cycler==0.10.0
    - databricks-cli==0.14.3
    - dataproperty==0.50.1
    - dataset==1.4.5
    - datasets==1.4.1
    - defusedxml==0.7.1
    - dill==0.3.3
    - distro==1.5.0
    - docker==4.4.4
    - dotnetcore2==2.1.20
    - entrypoints==0.3
    - executing==0.5.4
    - filelock==3.0.12
    - flask==1.1.2
    - fsspec==0.8.7
    - future==0.18.2
    - fuzzy-match==0.0.1
    - fuzzywuzzy==0.18.0
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth==1.27.1
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - gunicorn==20.1.0
    - huggingface-hub==0.0.2
    - icecream==2.1.0
    - idna==2.10
    - imageio==2.9.0
    - ipywidgets==7.6.3
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jeepney==0.6.0
    - jinja2==2.11.3
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonpickle==2.0.0
    - jsonschema==3.2.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - mako==1.1.4
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mbstrdecoder==1.0.1
    - mistune==0.8.4
    - mlflow==1.15.0
    - msal==1.10.0
    - msal-extensions==0.2.2
    - msgfy==0.1.0
    - msrest==0.6.21
    - msrestazure==0.6.4
    - multiprocess==0.70.11.1
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - ndg-httpsclient==0.5.1
    - nest-asyncio==1.5.1
    - nlp==0.4.0
    - nltk==3.5
    - notebook==6.3.0
    - numpy==1.20.1
    - oauthlib==3.1.0
    - packaging==20.9
    - pandas==1.2.3
    - pandocfilters==1.4.3
    - pathspec==0.8.1
    - pathvalidate==2.4.1
    - pillow==8.1.2
    - portalocker==1.7.1
    - prometheus-client==0.9.0
    - prometheus-flask-exporter==0.18.1
    - protobuf==3.15.5
    - pyarrow==1.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pycparser==2.20
    - pyjwt==2.0.1
    - pyopenssl==20.0.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytablewriter==0.58.0
    - python-editor==1.0.4
    - pytorch-lightning==0.8.5
    - pytz==2021.1
    - pyyaml==5.4.1
    - querystring-parser==1.2.4
    - regex==2020.11.13
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rouge-score==0.0.4
    - rsa==4.7.2
    - ruamel-yaml==0.17.2
    - ruamel-yaml-clib==0.2.2
    - sacremoses==0.0.43
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - secretstorage==3.3.1
    - send2trash==1.5.0
    - sentencepiece==0.1.95
    - sklearn==0.0
    - smmap==4.0.0
    - sqlalchemy==1.3.23
    - sqlparse==0.4.1
    - tabledata==1.1.3
    - tabulate==0.8.9
    - tcolorpy==0.0.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - terminado==0.9.4
    - test-tube==0.7.5
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tokenizers==0.8.1rc2
    - toml==0.10.2
    - torch==1.8.0
    - torchsummaryx==1.3.0
    - torchtext==0.9.0
    - torchviz==0.0.1
    - tqdm==4.49.0
    - transformers==3.1.0
    - typepy==1.1.4
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - webencodings==0.5.1
    - websocket-client==0.58.0
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - xxhash==2.0.0

